### ISSUE TITLE
Looking for fancy printing solutions 

### ISSUE THREAD

**Issue by vfulco** [t04glovern/aws-amplify-resume#1]
One of biggest issues for online resume users is being able to extend use cases into exact copy printing in pdf and docx.  Especially the latter.

Would appreciate if anyone has ideas on this while I grub around google.  I have tried browser based which doesn't work well.  Also seen headless processes but I am guessing the same.  Believe it comes down to having a separate .css file (???).  Pandoc can be used but then requires a separate ms word reference template and I have not figured how to pass in serverlessly yet.

Thanks in advance.

**Comment by t04glovern** [comment]
You would be correct in assuming you'd be looking at separate .css files; however since this project is build with React there are some good libraries to deal with this for you.

https://www.npmjs.com/package/react-to-print

I've used this one in the past for other projects and found it to be great. I might look into including it in this project

**Comment by vfulco** [comment]
That's terrific.  Thanks for the trailhead.  Will give it a try.
